# Generated by Django 4.0.4 on 2023-01-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default=True, max_length=255, null=True, unique=True, verbose_name='email')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('university', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('W', '여')], max_length=2)),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='phone')),
                ('date_of_birth', models.DateField()),
                ('pet_name', models.CharField(blank=True, default='', max_length=255, verbose_name='pet_name')),
                ('pet_gender', models.CharField(blank=True, choices=[('M', '수컷'), ('W', '암컷')], max_length=2)),
                ('pet_breed', models.CharField(blank=True, max_length=255, verbose_name='pet_breed')),
                ('pet_weight', models.CharField(blank=True, max_length=255, verbose_name='pet_weight')),
                ('pet_neuter', models.CharField(blank=True, choices=[('YES', '여'), ('NO', '부')], max_length=20)),
                ('pet_date_of_birth', models.DateField(blank=True, null=True, verbose_name='pet_date_of_birth')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
