# Generated by Django 4.0.4 on 2022-10-10 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('W', '여')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_breed',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='pet_breed'),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pet_gender',
            field=models.CharField(blank=True, choices=[('M', '수컷'), ('W', '암컷')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='pet_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_neuter',
            field=models.CharField(blank=True, choices=[('YES', '여'), ('NO', '부')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_weight',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='pet_weight'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='name'),
        ),
    ]
