# Generated by Django 4.0.4 on 2022-12-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pet_date_of_birth',
            field=models.DateField(default='', null=True, verbose_name='pet_date_of_birth'),
        ),
    ]
