# Generated by Django 4.0.4 on 2022-12-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_pet_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pet_date_of_birth',
            field=models.DateField(null=True, verbose_name='pet_date_of_birth'),
        ),
    ]
