# Generated by Django 4.1 on 2022-08-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='이름')),
                ('name_color', models.TextField(blank=True, null=True, verbose_name='이름 색')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='담당업무')),
                ('content1_color', models.TextField(blank=True, null=True, verbose_name='담당업무 색')),
                ('content2', models.TextField(blank=True, null=True, verbose_name='기타업무')),
                ('content2_color', models.TextField(blank=True, null=True, verbose_name='기타업무 색')),
                ('business_name', models.TextField(blank=True, null=True, verbose_name='회사 명')),
                ('business_name_color', models.TextField(blank=True, null=True, verbose_name='회사 명 색')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_img', verbose_name='프로필 이미지')),
                ('background_color', models.TextField(blank=True, null=True, verbose_name='배경색')),
            ],
        ),
    ]
