# Generated by Django 4.0.4 on 2022-08-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_difficult_remove_mission_complete_mission_en_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difficult',
        ),
        migrations.AddField(
            model_name='mission',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], null=True),
        ),
    ]
