# Generated by Django 4.0.4 on 2022-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_delete_difficult_mission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Normal'), (4, 'Difficult'), (5, 'Very Difficult')], null=True),
        ),
    ]
