# Generated by Django 4.0.4 on 2022-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='create',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='img_one',
            field=models.ImageField(blank=True, null=True, upload_to='img_one', verbose_name='이미지 첨부'),
        ),
    ]
