# Generated by Django 4.0.4 on 2022-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0008_remove_community_img_one_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_one', verbose_name='이미지 첨부'),
        ),
        migrations.AlterField(
            model_name='community',
            name='create',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
