# Generated by Django 4.0.4 on 2022-08-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0009_remove_answer_title_community_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_one', verbose_name='이미지 첨부'),
        ),
    ]
