# Generated by Django 4.0.4 on 2022-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0010_alter_community_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='이미지 첨부'),
        ),
    ]
