# Generated by Django 4.0.4 on 2022-08-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0012_alter_community_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='counting',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='community',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='이미지 첨부'),
        ),
    ]
