# Generated by Django 4.0.4 on 2022-08-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0013_alter_community_counting_alter_community_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.community')),
            ],
        ),
    ]
