# Generated by Django 4.0.4 on 2022-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0014_saveip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('en_title', models.CharField(blank=True, max_length=220, null=True)),
                ('summary', models.CharField(blank=True, max_length=220, null=True, verbose_name='요약')),
                ('materials', models.CharField(blank=True, max_length=220, null=True, verbose_name='준비물')),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
