# Generated by Django 4.0.4 on 2022-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0015_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='이미지 첨부'),
        ),
    ]
