# Generated by Django 4.0.4 on 2022-09-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0016_life_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='profile_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_img/', verbose_name='이미지 첨부'),
        ),
    ]
