# Generated by Django 4.0.4 on 2022-09-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0019_remove_saveip_text_community_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Life_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.life')),
            ],
        ),
    ]
