# Generated by Django 4.0.4 on 2022-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0020_life_text_life_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='life_detail',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='life_detail',
            name='title',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
