# Generated by Django 4.0.4 on 2022-09-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0021_life_detail_text_life_detail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='life_detail',
            old_name='text',
            new_name='sub_text',
        ),
        migrations.RenameField(
            model_name='life_detail',
            old_name='title',
            new_name='sub_title',
        ),
    ]
