# Generated by Django 4.0.4 on 2022-09-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0022_rename_text_life_detail_sub_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='이미지 첨부')),
            ],
        ),
    ]
