# Generated by Django 4.0.4 on 2022-09-30 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0023_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='en_title',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='title',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.CreateModel(
            name='Pack_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='이미지 첨부')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('en_name', models.CharField(blank=True, max_length=220, null=True)),
                ('price', models.CharField(blank=True, max_length=220, null=True)),
                ('important', models.BooleanField(default=False)),
                ('pack_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.pack')),
            ],
        ),
    ]
