# Generated by Django 4.0.4 on 2022-09-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0024_pack_en_title_pack_title_pack_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack_detail',
            name='access_ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
