# Generated by Django 4.0.4 on 2022-09-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0025_pack_detail_access_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack_detail',
            old_name='pack_detail',
            new_name='pack',
        ),
    ]
