# Generated by Django 4.0.4 on 2022-10-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0026_rename_pack_detail_pack_detail_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=220, null=True)),
                ('sub_text', models.TextField(blank=True, null=True)),
                ('access_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.mission')),
            ],
        ),
    ]
