# Generated by Django 4.0.4 on 2022-10-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0027_mission_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission_detail',
            old_name='life',
            new_name='mission',
        ),
    ]
