# Generated by Django 4.1 on 2022-08-16 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/feeds/%Y/%m/%d', verbose_name='이미지')),
                ('profile_imge', models.ImageField(blank=True, null=True, upload_to='uploads/feeds/%Y/%m/%d', verbose_name='프로필 이미지')),
                ('like_count', models.IntegerField(blank=True, null=True, verbose_name='좋아요 수')),
                ('name', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '피드',
                'verbose_name_plural': '피드',
                'db_table': 'feeds',
            },
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.feed', verbose_name='피드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='좋아요한 유저')),
            ],
            options={
                'verbose_name': '피드 좋아요',
                'verbose_name_plural': '피드 좋아요',
                'db_table': 'feed_like',
            },
        ),
    ]
